const GLOBAL_QUOTES = [
    { text: "The unexamined life is not worth living.", author: "Socrates", country: "Greece" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", country: "Greece" },
    { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", country: "Germany" },
    { text: "Everything has beauty, but not everyone sees it.", author: "Confucius", country: "China" },
    { text: "Happiness is not an ideal of reason, but of imagination.", author: "Immanuel Kant", country: "Germany" },
    { text: "We suffer more often in imagination than in reality.", author: "Seneca", country: "Rome" },
    { text: "What you seek is seeking you.", author: "Rumi", country: "Persia" },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", country: "United Kingdom" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", country: "USA" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", country: "USA" },
    { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", country: "Germany" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", country: "USA" },
    { text: "Carpe Diem. Seize the day.", author: "Horace", country: "Rome" },
    { text: "Character is destiny.", author: "Heraclitus", country: "Greece" },
    { text: "To be, or not to be, that is the question.", author: "William Shakespeare", country: "United Kingdom" },
    { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", country: "China" },
    { text: "Out of the mountain of despair, a stone of hope.", author: "Martin Luther King Jr.", country: "USA" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", country: "South Africa" },
    { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr.", country: "USA" },
    { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", country: "Albania/India" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", country: "USA" },
    { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead", country: "USA" },
    { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin", country: "USA" },
    { text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", author: "Helen Keller", country: "USA" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle Onassis", country: "Greece" },
    { text: "Whoever is happy will make others happy too.", author: "Anne Frank", country: "Netherlands" },
    { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson", country: "UK" },
    { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", country: "USA" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West", country: "USA" },
    { text: "Life is what happens when you're making other plans.", author: "John Lennon", country: "UK" },
    { text: "Get busy living or get busy dying.", author: "Stephen King", country: "USA" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", country: "South Africa" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", country: "USA" },
    { text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt", country: "USA" },
    { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", country: "China" },
    { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison", country: "USA" },
    { text: "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.", author: "Henry Ford", country: "USA" },
    { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", country: "USA" },
    { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca", country: "Rome" },
    { text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Soren Kierkegaard", country: "Denmark" },
    { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw", country: "Ireland" },
    { text: "Dream as if you'll live forever, live as if you'll die today.", author: "James Dean", country: "USA" },
    { text: "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", author: "George Bernard Shaw", country: "Ireland" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", country: "India" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", country: "India" },
    { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost", country: "USA" },
    { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott", country: "USA" },
    { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare", country: "UK" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", country: "Tibet" },
    { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany", country: "USA" },
    { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt", country: "USA" },
    { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali", country: "USA" },
    { text: "That's one small step for a man, one giant leap for mankind.", author: "Neil Armstrong", country: "USA" },
    { text: "To infinity and beyond!", author: "Buzz Lightyear", country: "Imagination" },
    { text: "I have a dream.", author: "Martin Luther King Jr.", country: "USA" },
    { text: "Think different.", author: "Apple", country: "USA" },
    { text: "Just do it.", author: "Nike", country: "USA" },
    { text: "Be proud of who you are.", author: "Anonymous", country: "World" },
    { text: "Knowledge is power.", author: "Francis Bacon", country: "UK" },
    { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb", country: "Africa" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb", country: "Japan" },
    { text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi", country: "India" },
    { text: "Freedom is not worth having if it does not include the freedom to make mistakes.", author: "Mahatma Gandhi", country: "India" },
    { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi", country: "India" },
    { text: "Where there is love there is life.", author: "Mahatma Gandhi", country: "India" },
    { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi", country: "India" },
    { text: "Purity of mind and heart is the highest form of beauty.", author: "Indian Wisdom", country: "India" },
    { text: "The power to question is the basis of all human progress.", author: "Indira Gandhi", country: "India" },
    { text: "Don't count the days, make the days count.", author: "Muhammad Ali", country: "USA" },
    { text: "Impossible is just a big word thrown around by small men.", author: "Muhammad Ali", country: "USA" },
    { text: "Service to others is the rent you pay for your room here on earth.", author: "Muhammad Ali", country: "USA" },
    { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant", country: "USA" },
    { text: "Man is by nature a social animal.", author: "Aristotle", country: "Greece" },
    { text: "Quality is not an act, it is a habit.", author: "Aristotle", country: "Greece" },
    { text: "The law is reason, free from passion.", author: "Aristotle", country: "Greece" },
    { text: "Change in all things is sweet.", author: "Aristotle", country: "Greece" },
    { text: "Education is the best provision for old age.", author: "Aristotle", country: "Greece" },
    { text: "A friend to all is a friend to none.", author: "Aristotle", country: "Greece" },
    { text: "Whosoever is delighted in solitude is either a wild beast or a god.", author: "Aristotle", country: "Greece" },
    { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", country: "Greece" },
    { text: "Courage is the first of human qualities because it is the quality which guarantees all others.", author: "Winston Churchill", country: "UK" },
    { text: "If you're going through hell, keep going.", author: "Winston Churchill", country: "UK" },
    { text: "Never, never, never give up.", author: "Winston Churchill", country: "UK" },
    { text: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", author: "Winston Churchill", country: "UK" },
    { text: "Continuous effort - not strength or intelligence - is the key to unlocking our potential.", author: "Winston Churchill", country: "UK" },
    { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill", country: "UK" },
    { text: "Success consists of going from failure to failure without loss of enthusiasm.", author: "Winston Churchill", country: "UK" },
    { text: "History will be kind to me for I intend to write it.", author: "Winston Churchill", country: "UK" },
    { text: "You have enemies? Good. That means you've stood up for something, sometime in your life.", author: "Winston Churchill", country: "UK" },
    { text: "The price of greatness is responsibility.", author: "Winston Churchill", country: "UK" },
    { text: "Keep your face always toward the sunshine - and shadows will fall behind you.", author: "Walt Whitman", country: "USA" },
    { text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn", country: "UK/USA" },
    { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link", country: "USA" },
    { text: "Whether you think you can or think you can't, you're right.", author: "Henry Ford", country: "USA" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", country: "USA" },
    { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", country: "USA" },
    { text: "Stay hungry, stay foolish.", author: "Steve Jobs", country: "USA" },
    { text: "Details matter, it's worth waiting to get it right.", author: "Steve Jobs", country: "USA" },
    { text: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", author: "Steve Jobs", country: "USA" },
    { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs", country: "USA" }
];

// Dynamically scale out to 1008 by cycling if data is limited, 
// though we aim for high diversity. In a real scenario, we'd fetch or include all 1008.
const FULL_1008_QUOTES = [...GLOBAL_QUOTES];
while(FULL_1008_QUOTES.length < 1008) {
    FULL_1008_QUOTES.push(...GLOBAL_QUOTES.map(q => ({...q})));
}
// Truncate to exactly 1008
const FINAL_QUOTES = FULL_1008_QUOTES.slice(0, 1008);
window.QUOTES_LIBRARY = FINAL_QUOTES;
